name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours
  workflow_dispatch:     # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Arefin-Saiful
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
